panel/urls.py
from django.contrib import admin
from django.urls import path, include
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('streaming.urls')),
]

streaming/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from . import views
urlpatterns = [
    path('', views.videos, name='video'),
    path('inicio', views.inicio, name='inicio'),
    path('administrador', views.administrador, name='administrador'),
    path('registrar_video', views.registrar_video, name='registrar_video'),
    path('editar_name_video/<int:video_id>', views.editar_name_video, name='editar_name_video'),
    path('eliminar_video/<int:video_id>' , views.eliminar_video, name='eliminar_video'),
    path('usuarios', views.usuarios, name='usuarios'),
    path('registrar_usuario', views.registrar_usuario , name='registrar_usuario'),
    path('registrar_grupo', views.registrar_grupo , name='registrar_grupo'),
    path('eliminar_user_admin/<int:id>', views.eliminar_user_admin , name='eliminar_user_admin'),
    path('edit_user/<int:id>', views.edit_user, name='edit_user'),
    path('espacio_disco', views.espacio_disco, name='espacio_disco'),
    path('perfil', views.perfil, name='perfil'),
    path('history', views.history, name='history'),
    path('logout', views.logout_view, name='logout'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
]

streaming/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Videos(models.Model):
    
    video_id = models.AutoField(db_column='video_id', primary_key=True)
    video_name = models.CharField(max_length=100)
    location = models.FileField(upload_to='video/')
    fecha = models.CharField(max_length=50) 

    class Meta:
        db_table = 'video'
        
        
class Historial(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    descripcion_historial = models.TextField(max_length=200)
    tabla_afectada_historial = models.TextField(max_length=100)
    fecha_hora_historial = models.DateTimeField()

streaming/views.py
from datetime import datetime
import os
from django.contrib import messages 
import shutil
from django.conf import settings
from django.shortcuts import redirect, render
from .models import Videos, Historial
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login ,logout 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm 
from django.contrib.auth.models import User ,Group , Permission
from django.db import transaction
from math import log, floor
from django.contrib.auth.decorators import permission_required


def videos(request):
    videos = Videos.objects.all()
    return render(request, 'paginas/videos.html', {'videos': videos})

def inicio(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                
              
                usuario = request.user.id
                
                descripcion = "Inicia Sesión"
                tabla = "" 
                fechayhora = datetime.now()
                
                try:
                    his = Historial(descripcion_historial=descripcion, tabla_afectada_historial=tabla, fecha_hora_historial=fechayhora, usuario_id=usuario)
                    his.save()
                except Exception as e:
                    # Es buena práctica manejar errores al guardar en el historial
                    print(f"Error al guardar en el historial: {e}")
                
                return redirect('administrador')
            else:
                return render(request, 'paginas/login.html', {'form': form, 'error': 'Usuario o contraseña incorrectos'})
        else:
            return render(request, 'paginas/login.html', {'form': form, 'error': 'Usuario o contraseña incorrectos'})
    else:
        form = AuthenticationForm()
        return render(request, 'paginas/login.html', {'form': form})
    
@login_required
@permission_required('streaming.view_videos', raise_exception=True)
def administrador(request):
    videos = Videos.objects.all()
    return render(request, 'paginas/administrador.html', {'videos': videos})

def registrar_video(request):
    if request.method == 'POST':
        
        new_video_name = request.POST.get('name')
        uploaded_file = request.FILES.get('video')
        
       
        if not uploaded_file or not new_video_name:
            messages.error(request, 'Debes proporcionar un nombre y un archivo de video.')
            return redirect('administrador')
        
        
        extension = os.path.splitext(uploaded_file.name)[1]
        
      
        file_name = f"{new_video_name}{extension}"
        uploaded_file.name = file_name
        
        
        try:
            video = Videos(video_name=new_video_name, location=uploaded_file)
            video.save()
            
          
            if request.user.is_authenticated:
                usuario = request.user.id
                descripcion = (f"Registro del video: {new_video_name}")  
                tabla = "Videos" 
                fechayhora = datetime.now()
                
                historial_entry = Historial(
                    descripcion_historial=descripcion,
                    tabla_afectada_historial=tabla,
                    fecha_hora_historial=fechayhora,
                    usuario_id=usuario
                )
                historial_entry.save()
                
            messages.success(request, f'El video {new_video_name} fue guardado exitosamente.')
        except Exception as e:
            
            print(f"Error al guardar el video o el historial: {e}")
            messages.error(request, 'Ocurrió un error al guardar el video. Inténtalo de nuevo.')
            
        return redirect('administrador')
    
    # Si la solicitud no es POST, simplemente renderiza la página
    return render(request, 'paginas/administrador.html')
   
def editar_name_video(request, video_id): 
    
    video = get_object_or_404(Videos, video_id=video_id)

    if request.method == 'POST':
        try:
            new_video_name = request.POST.get('video_name')
            
            
            if new_video_name:
                video.video_name = new_video_name
                video.save()
                if request.user.is_authenticated:
                    usuario = request.user.id
                    descripcion = (f"edito el nombre del video {new_video_name}")  
                    tabla = "Videos" 
                    fechayhora = datetime.now()
                    
                    historial_entry = Historial(
                        descripcion_historial=descripcion,
                        tabla_afectada_historial=tabla,
                        fecha_hora_historial=fechayhora,
                        usuario_id=usuario
                    )
                    historial_entry.save()
                messages.success(request, f'El nombre del video fue actualizado exitosamente a {new_video_name}.')
            else:
                
                messages.info(request, 'No se proporcionó un nuevo nombre. El nombre del video se mantuvo sin cambios.')
            
            return redirect('administrador')
        
        except Exception as e:
            messages.error(request, f'Ocurrió un error al actualizar el nombre: {e}')
            return redirect('usuarios')
    
    return render(request, 'paginas/admin.html', {'video': video})


def eliminar_video(request, video_id):
    
    video = get_object_or_404(Videos, video_id=video_id)
    
   
    if request.method == 'GET':
        video_titulo = video.video_name
        video.delete()
        if request.user.is_authenticated:
                usuario = request.user.id
                descripcion = ( f'elimino el video: {video_titulo}')  
                tabla = "Videos" 
                fechayhora = datetime.now()
                
                historial_entry = Historial(
                    descripcion_historial=descripcion,
                    tabla_afectada_historial=tabla,
                    fecha_hora_historial=fechayhora,
                    usuario_id=usuario
                )
                historial_entry.save()
        messages.success(request, f'El video {video_titulo} fue eliminado exitosamente.')
        return redirect('administrador')
    return render(request, 'paginas/administrador.html', {'video': video})


@login_required
@permission_required('auth.view_user', raise_exception=True)
def usuarios(request):
    groups  = Group.objects.all()
    usuarios = User.objects.all()
    permiso = Permission.objects.all()
    contexto ={
        'usuarios': usuarios , 'groups':  groups , 'permiso': permiso
    }
    return render(request, 'paginas/usuarios.html', contexto)


def registrar_usuario(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name', '').strip()
        username = request.POST.get('username', '').strip()
        password = request.POST.get('password', '').strip()
        rol_id = request.POST.get('rol')
        
        
        if not all([first_name, username, password, rol_id]):
            messages.error(request, 'Todos los campos son obligatorios.')
            return redirect('usuarios')
        
        
        if len(password) < 8:
            messages.error(request, 'La contraseña debe tener al menos 8 caracteres.')
            return redirect('usuarios')
            
        
        if not username.isalnum():
            messages.error(request, 'El nombre de usuario solo puede contener letras y números.')
            return redirect('usuarios')
            
        
        if User.objects.filter(username__iexact=username).exists():
            messages.error(request, 'El nombre de usuario ya existe. Por favor, elige otro.')
            return redirect('usuarios')

        try:
        
            with transaction.atomic():
             
                new_user = User.objects.create_user(
                    first_name = first_name,
                    username=username,
                    password=password,
                )

                
                rol_instance = get_object_or_404(Group, id=rol_id)
                new_user.groups.add(rol_instance)
                 
                if request.user.is_authenticated:
                    usuario = request.user.id
                    descripcion = ( f'se registro el usuaio : {username}')  
                    tabla = "auth_user" 
                    fechayhora = datetime.now()
                    
                    historial_entry = Historial(
                        descripcion_historial=descripcion,
                        tabla_afectada_historial=tabla,
                        fecha_hora_historial=fechayhora,
                        usuario_id=usuario
                    )
                    historial_entry.save()

                messages.success(request, f'El usuario {username} ha sido registrado exitosamente.')
                return redirect('usuarios')
            
        except Exception as e:
            messages.error(request, f'Error inesperado al registrar el usuario: {str(e)}')
            return redirect('usuarios')
        
    return render(request, 'paginas/usuarios.html')


def registrar_grupo(request):
    if request.method == 'POST':
        nombre_rol = request.POST.get('nombre_rol')
        permisos_seleccionados = request.POST.getlist('permisos')

        if not nombre_rol:
            messages.error(request, 'El nombre del rol no puede estar vacío.')

streaming/templates/paginas/administrador.html
{% extends "base/dashboard.html" %}

{% block titulo %}MercalStream - Videos{% endblock %}

{% block content %}
<div id="layoutSidenav_content">

    {% if messages %}
    {% for message in messages %}
    <script>
        Swal.fire({
            title: '{{ message.tags|title }}',
            text: '{{ message }}',
            icon: '{{ message.tags }}'
        });
    </script>
    {% endfor %}
    {% endif %}

    <main>
        <div class="container-fluid px-4">
            <div class="d-flex justify-content-between align-items-center mt-4 mb-4">
                {% if perms.streaming.view_videos %}
                <h3 class="mb-0">MercalStream - Videos</h3>
                {% endif %}
                {% if perms.streaming.add_videos %}
                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Nuevo Video
                </button>
                {% endif %}
            </div>
            {% include 'modal/registrar_video.html' %}


            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
                {% for video in videos %}
                <div class="col">
                   {% if perms.streaming.view_videos %}
                        <div class="card h-100">
                            <video class="card-img-top" controls>
                                <source src="{{ video.location.url }}" type="video/mp4">
                                Tu navegador no soporta la etiqueta de video.
                            </video>
                            <div class="card-body">
                                <h5 class="card-title text-center">{{ video.video_name }}</h5>
                            </div>
                            <div class="card-footer d-flex justify-content-center">
                                {% if perms.streaming.add_videos %}
                                <a href="#" class="btn btn-warning me-2" data-bs-toggle="modal"
                                    data-bs-target="#editarvideos{{ video.video_id }}">
                                    Editar
                                </a>
                                {% endif %}
                                {% if perms.streaming.delete_videos %}
                                {% url 'eliminar_video' video.video_id as ruta %}
                                <a href="#" class="btn btn-danger"
                                    onclick="confirmarEliminar(event, '{{ruta}}')">Eliminar</a>
                                {% endif %}
                                <script>
                                    function confirmarEliminar(event, url) {
                                        event.preventDefault(); // Evita que el enlace navegue inmediatamente

                                        Swal.fire({
                                            title: '¿Estás seguro?',
                                            text: '¡No podrás revertir esto!',
                                            icon: 'warning',
                                            showCancelButton: true,
                                            confirmButtonColor: '#d33',
                                            cancelButtonColor: '#3085d6',
                                            confirmButtonText: 'Sí, ¡elimínalo!',
                                            cancelButtonText: 'Cancelar'
                                        }).then((result) => {
                                            if (result.isConfirmed) {
                                                window.location.href = url; // Redirige a la URL de eliminación si el usuario confirma
                                            }
                                        });
                                    }
                                </script>
                            </div>
                    </div>
                    {% endif %}
                </div>
                {% include 'modal/editar_video.html' %}
                {% endfor %}
            </div>

            <nav aria-label="Paginación" class="mt-4">
                <ul class="pagination justify-content-center">
                </ul>
            </nav>
        </div>
    </main>
</div>
{% endblock %}

streaming/templates/paginas/espacio.html
{% extends "base/dashboard.html" %}

{% block titulo %}MercalStream - Estado del Disco{% endblock %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4 py-8">
            <h1 class="text-3xl font-bold mb-8 text-center text-emphasis-dark">
                Espacio del Disco
            </h1>

            {% if main_disk_data %}
            <div class="card bg-body-tertiary rounded-lg shadow-lg p-5 mt-5">
                <div class="d-flex justify-content-between mb-2">
                    <span class="text-muted small">Última actualización: {{ main_disk_data.last_updated }}</span>
                </div>

                <div class="row p-6">
                    <div class="col-md-4 mb-4">
                        <div class="bg-primary text-white p-4 rounded-lg">
                            <div class="font-weight-bold">Total</div>
                            <div class="h2">{{ main_disk_data.total }}</div>
                            <div class="small">{{ main_disk_data.total }} disponible</div>
                        </div>
                    </div>

                    <div class="col-md-4 mb-4">
                        <div class="bg-success text-white p-4 rounded-lg">
                            <div class="font-weight-bold">Libre</div>
                            <div class="h2">{{ main_disk_data.free }}</div>
                            <div class="small">{{ main_disk_data.percentage_free }}% disponible</div>
                        </div>
                    </div>

                    <div class="col-md-4 mb-4">
                        <div class="bg-danger text-white p-4 rounded-lg">
                            <div class="font-weight-bold">En uso</div>
                            <div class="h2">{{ main_disk_data.used }}</div>
                            <div class="small">{{ main_disk_data.percentage_used }}% utilizado</div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}

            <div class="card bg-body-tertiary rounded-lg shadow-lg px-5 mt-2">
                <br>
                <h2 class="h4 font-weight-semibold mb-4 text-emphasis-dark">Particiones del sistema</h2>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead class="thead-light">
                            <tr>
                                <th>Partición</th>
                                <th>Total</th>
                                <th>Libre</th>
                                <th>En uso</th>
                                <th>%</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for partition in partitions %}
                            <tr>
                                <td>{{ partition.name }}</td>
                                <td>{{ partition.total }}</td>
                                <td>{{ partition.free }}</td>
                                <td>{{ partition.used }}</td>
                                <td>
                                    </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="5">No se pudo obtener la información de las particiones.</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

streaming/templates/paginas/history.html
{% extends "base/dashboard.html" %}

{% block titulo %}MercalStream - Videos{% endblock %}

{% block content %}
<div id="layoutSidenav_content">


    <main>
       <br>
        <br>
        <div class="conta card">
            <h2>Historial</h2>
           
               
            <div class="controls">
                <input type="text" id="searchInput" placeholder="Buscar usuario...">
                <select id="rowsPerPage">
                    <option value="5">5 por página</option>
                    <option value="10">10 por página</option>
                    <option value="20">20 por página</option>
                </select>
            </div>

            <table id="myTable" class="table table-hover table-striped table-responsive">
                <thead>
                    {{ tabla_afectada_historial }}
                    <tr>
                        <th>Usuario</th>
                        <th>Accion</th>
                        
                        <th>Tabla</th>
                        
                        <th>Fecha y Hora</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in historial %}
                    <tr>
                       <td>{{ x.usuario.username }}</td>
							<td>{{ x.descripcion_historial }}</td>
                            
							<td>{{ x.tabla_afectada_historial }}</td>
                            
						<td>{{ x.fecha_hora_historial }}</td>

                       
                    </tr>

                  
                    {% endfor %}

                </tbody>
            </table>

            <div class="pagination">
                <button id="prevBtn">Anterior</button>
                <h6 id="pageNumbers"></h6>
                <button id="nextBtn">Siguiente</button>
            </div>
        </div>
    </main>
</div>
{% endblock %}

streaming/templates/paginas/login.html
{% extends 'base/login.html' %}
{% block titulo %} Login {% endblock %}

{% block content %}
                   
                  <form action="inicio" method="POST" class="m-auto" style="width: 90%">
                    {% csrf_token %}
                    <p class="text-center">Por favor, ingresa tus credenciales</p>

                    <div class="form-group mb-4">
                      <i class="fas fa-user form-control-feedback"></i>
                      <input type="text" name="username" maxlength="10" required class="form-control my-input" placeholder="Usuario">
                    </div>

                    <div class="form-outline mb-4">
                      <i class="fas fa-lock form-control-feedback"></i>
                      <input type="password" name="password" required maxlength="10" class="form-control my-input" placeholder="Contraseña">
                    </div>

                    <div class="text-center pt-1 mb-5 pb-1">
                      <button class="btn btn-outline-primary btn-custom fa-lg mb-3" type="submit" style="padding: 10px 0; width: 100%;">Ingresar</button>
                      <a class="stri" href="{% url 'video' %}">streaming</a>
                    </div>
                  </form>
                  <p class="text-muted text-center">&copy; Mercal C.A 2025</p>
{% endblock %}

               

streaming/templates/paginas/perfil.html
{% extends "base/dashboard.html" %}

{% block titulo %} MercalStream -perfil  {% endblock %}

{% block content %}

   <!--- {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}  ----->

    {% if messages %}
           {% for message in messages %}
               <script>
                   Swal.fire({
                       title: '{{ message.tags|title }}',
                       text: '{{ message }}',
                       icon: '{{ message.tags }}'
                   });
               </script>
           {% endfor %}
       {% endif %}

    <div class="co">
        <div class="profile-header card">

            <div class="follow-btn" data-bs-toggle="modal" data-bs-target="#exampleModal" >Cambiar Contraseña</div>
            
            <img src="../../../static/img/perf.png" alt="Retrato profesional de un hombre con traje gris y corbata azul, fondo de oficina moderna" class="profile-photo">
            
            <h1 class="profile-name"></h1>
            <h2 class="profile-title">
                {% if request.user.groups.all %}
                    {{ request.user.groups.all.0.name }}
                {% else %}
                    Sin grupo
                {% endif %}
                </h2>

           <div class="row g-2">
                    <div class="col-md-6 col-sm-12"> 
                        <label for="">Nombre</label>
                        <div class="input-group">
                            <input type="text" class="form-control disabled" value="{{ request.user.first_name }}" disabled>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12"> 
                        <label for="">Apellido</label>
                        <div class="input-group">
                            <input type="text" class="form-control disabled" value="{{ request.user.last_name }}" disabled>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12"> 
                        <label for="">usuario</label>
                        <div class="input-group">
                            <input type="text" class="form-control disabled" value="{{ request.user.username }}" disabled>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <label for="">correo</label> 
                        <div class="input-group">
                            <input type="text" class="form-control disabled" value="{{ request.user.email }}" disabled>
                        </div>
                    </div>
                </div>
            </div>
        
       
       
    </div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Cambiar Contraseña</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="cambio_pass" method="post">
             {% csrf_token %}
        <label for="">Contraseña actual</label>
           <input type="text" class="form-control" name="current_password">
        <label for="">Nueva Contraseña</label>
         <input type="text" class="form-control" name="new_password">
        <label for="">confirmar Contraseña</label>
         <input type="text" class="form-control" name="confirm_password">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Cambiar</button>
      </div>
    
    </form>
    </div>
  </div>
</div>


{% endblock %}

streaming/templates/paginas/videos.html
{% extends 'base/videos.html' %}
{% block title %}Videos{% endblock %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6">
                {% if videos %}
                    <div id="video-player-container" class="text-center">
                        <img src="../../../static/img/logo.png" class="logo" alt="Logo">
                        
                        {% for video in videos %}
                            <video class="video-item w-100 mb-3" controls style="display: none;">
                                <source src="{{ video.location.url }}" type="video/mp4">
                            </video>
                        {% endfor %}
                        
                        <div class="video-controls d-flex justify-content-between">
                            <button id="prev-btn" class="btn btn-primary">Anterior</button>
                            <a class="btn btn-primary" href="{% url 'inicio' %}">Inicio</a>
                            <button id="next-btn" class="btn btn-primary">Siguiente</button>
                        </div>
                    </div>
                {% else %}
                    <p class="text-center">No hay videos disponibles.</p>
                {% endif %}
            </div>
        </div>

   
    </div>
{% endblock %}