panel/urls.py
from django.contrib import admin
from django.urls import path, include
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('streaming.urls')),
]

streaming/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from . import views
urlpatterns = [
    path('', views.videos, name='video'),
    path('inicio', views.inicio, name='inicio'),
    path('administrador', views.administrador, name='administrador'),
    path('registrar_video', views.registrar_video, name='registrar_video'),
    path('editar_name_video/<int:video_id>', views.editar_name_video, name='editar_name_video'),
    path('eliminar_video/<int:video_id>' , views.eliminar_video, name='eliminar_video'),
    path('usuarios', views.usuarios, name='usuarios'),
    path('registrar_usuario', views.registrar_usuario , name='registrar_usuario'),
    path('registrar_grupo', views.registrar_grupo , name='registrar_grupo'),
    path('eliminar_user_admin/<int:id>', views.eliminar_user_admin , name='eliminar_user_admin'),
    path('edit_user/<int:id>', views.edit_user, name='edit_user'),
    path('espacio_disco', views.espacio_disco, name='espacio_disco'),
    path('perfil', views.perfil, name='perfil'),
    path('history', views.history, name='history'),
    path('logout', views.logout_view, name='logout'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
]

streaming/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Videos(models.Model):
    
    video_id = models.AutoField(db_column='video_id', primary_key=True)
    video_name = models.CharField(max_length=100)
    location = models.FileField(upload_to='video/')
    fecha = models.CharField(max_length=50) 

    class Meta:
        db_table = 'video'
        
        
class Historial(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    descripcion_historial = models.TextField(max_length=200)
    tabla_afectada_historial = models.TextField(max_length=100)
    fecha_hora_historial = models.DateTimeField()

streaming/views.py
from datetime import datetime
import os
from django.contrib import messages 
import shutil
from django.conf import settings
from django.shortcuts import redirect, render
from .models import Videos, Historial
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login ,logout 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm 
from django.contrib.auth.models import User ,Group , Permission
from django.db import transaction
from math import log, floor
from django.contrib.auth.decorators import permission_required


def videos(request):
    videos = Videos.objects.all()
    return render(request, 'paginas/videos.html', {'videos': videos})

def inicio(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                
              
                usuario = request.user.id
                
                descripcion = "Inicia Sesión"
                tabla = "" 
                fechayhora = datetime.now()
                
                try:
                    his = Historial(descripcion_historial=descripcion, tabla_afectada_historial=tabla, fecha_hora_historial=fechayhora, usuario_id=usuario)
                    his.save()
                except Exception as e:
                    # Es buena práctica manejar errores al guardar en el historial
                    print(f"Error al guardar en el historial: {e}")
                
                return redirect('administrador')
            else:
                return render(request, 'paginas/login.html', {'form': form, 'error': 'Usuario o contraseña incorrectos'})
        else:
            return render(request, 'paginas/login.html', {'form': form, 'error': 'Usuario o contraseña incorrectos'})
    else:
        form = AuthenticationForm()
        return render(request, 'paginas/login.html', {'form': form})
    
@login_required
@permission_required('streaming.view_videos', raise_exception=True)
def administrador(request):
    videos = Videos.objects.all()
    return render(request, 'paginas/administrador.html', {'videos': videos})

def registrar_video(request):
    if request.method == 'POST':
        
        new_video_name = request.POST.get('name')
        uploaded_file = request.FILES.get('video')
        
       
        if not uploaded_file or not new_video_name:
            messages.error(request, 'Debes proporcionar un nombre y un archivo de video.')
            return redirect('administrador')
        
        
        extension = os.path.splitext(uploaded_file.name)[1]
        
      
        file_name = f"{new_video_name}{extension}"
        uploaded_file.name = file_name
        
        
        try:
            video = Videos(video_name=new_video_name, location=uploaded_file)
            video.save()
            
          
            if request.user.is_authenticated:
                usuario = request.user.id
                descripcion = (f"Registro del video: {new_video_name}")  
                tabla = "Videos" 
                fechayhora = datetime.now()
                
                historial_entry = Historial(
                    descripcion_historial=descripcion,
                    tabla_afectada_historial=tabla,
                    fecha_hora_historial=fechayhora,
                    usuario_id=usuario
                )
                historial_entry.save()
                
            messages.success(request, f'El video {new_video_name} fue guardado exitosamente.')
        except Exception as e:
            
            print(f"Error al guardar el video o el historial: {e}")
            messages.error(request, 'Ocurrió un error al guardar el video. Inténtalo de nuevo.')
            
        return redirect('administrador')
    
    # Si la solicitud no es POST, simplemente renderiza la página
    return render(request, 'paginas/administrador.html')
   
def editar_name_video(request, video_id): 
    
    video = get_object_or_404(Videos, video_id=video_id)

    if request.method == 'POST':
        try:
            new_video_name = request.POST.get('video_name')
            
            
            if new_video_name:
                video.video_name = new_video_name
                video.save()
                if request.user.is_authenticated:
                    usuario = request.user.id
                    descripcion = (f"edito el nombre del video {new_video_name}")  
                    tabla = "Videos" 
                    fechayhora = datetime.now()
                    
                    historial_entry = Historial(
                        descripcion_historial=descripcion,
                        tabla_afectada_historial=tabla,
                        fecha_hora_historial=fechayhora,
                        usuario_id=usuario
                    )
                    historial_entry.save()
                messages.success(request, f'El nombre del video fue actualizado exitosamente a {new_video_name}.')
            else:
                
                messages.info(request, 'No se proporcionó un nuevo nombre. El nombre del video se mantuvo sin cambios.')
            
            return redirect('administrador')
        
        except Exception as e:
            messages.error(request, f'Ocurrió un error al actualizar el nombre: {e}')
            return redirect('usuarios')
    
    return render(request, 'paginas/admin.html', {'video': video})


def eliminar_video(request, video_id):
    
    video = get_object_or_404(Videos, video_id=video_id)
    
   
    if request.method == 'GET':
        video_titulo = video.video_name
        video.delete()
        if request.user.is_authenticated:
                usuario = request.user.id
                descripcion = ( f'elimino el video: {video_titulo}')  
                tabla = "Videos" 
                fechayhora = datetime.now()
                
                historial_entry = Historial(
                    descripcion_historial=descripcion,
                    tabla_afectada_historial=tabla,
                    fecha_hora_historial=fechayhora,
                    usuario_id=usuario
                )
                historial_entry.save()
        messages.success(request, f'El video {video_titulo} fue eliminado exitosamente.')
        return redirect('administrador')
    return render(request, 'paginas/administrador.html', {'video': video})


@login_required
@permission_required('auth.view_user', raise_exception=True)
def usuarios(request):
    groups  = Group.objects.all()
    usuarios = User.objects.all()
    permiso = Permission.objects.all()
    contexto ={
        'usuarios': usuarios , 'groups':  groups , 'permiso': permiso
    }
    return render(request, 'paginas/usuarios.html', contexto)


def registrar_usuario(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name', '').strip()
        username = request.POST.get('username', '').strip()
        password = request.POST.get('password', '').strip()
        rol_id = request.POST.get('rol')
        
        
        if not all([first_name, username, password, rol_id]):
            messages.error(request, 'Todos los campos son obligatorios.')
            return redirect('usuarios')
        
        
        if len(password) < 8:
            messages.error(request, 'La contraseña debe tener al menos 8 caracteres.')
            return redirect('usuarios')
            
        
        if not username.isalnum():
            messages.error(request, 'El nombre de usuario solo puede contener letras y números.')
            return redirect('usuarios')
            
        
        if User.objects.filter(username__iexact=username).exists():
            messages.error(request, 'El nombre de usuario ya existe. Por favor, elige otro.')
            return redirect('usuarios')

        try:
        
            with transaction.atomic():
             
                new_user = User.objects.create_user(
                    first_name = first_name,
                    username=username,
                    password=password,
                )

                
                rol_instance = get_object_or_404(Group, id=rol_id)
                new_user.groups.add(rol_instance)
                 
                if request.user.is_authenticated:
                    usuario = request.user.id
                    descripcion = ( f'se registro el usuaio : {username}')  
                    tabla = "auth_user" 
                    fechayhora = datetime.now()
                    
                    historial_entry = Historial(
                        descripcion_historial=descripcion,
                        tabla_afectada_historial=tabla,
                        fecha_hora_historial=fechayhora,
                        usuario_id=usuario
                    )
                    historial_entry.save()

                messages.success(request, f'El usuario {username} ha sido registrado exitosamente.')
                return redirect('usuarios')
            
        except Exception as e:
            messages.error(request, f'Error inesperado al registrar el usuario: {str(e)}')
            return redirect('usuarios')
        
    return render(request, 'paginas/usuarios.html')


def registrar_grupo(request):
    if request.method == 'POST':
        nombre_rol = request.POST.get('nombre_rol')
        permisos_seleccionados = request.POST.getlist('permisos')

        if not nombre_rol:
            messages.error(request, 'El nombre del rol no puede estar vacío.')

streaming/templates/base/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="es" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %} {% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static './css/nuevo.css' %}">
    <link href="{% static './estilos/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome para iconos -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"> <!-- Cambia a un archivo local si es necesario -->
    <link rel="stylesheet" href="{% static './css/tablas.css' %}">
    <link rel="stylesheet" href="{% static './css/perfil.css' %}">
    <link rel="shortcut icon" href="{% static './img/logo.png' %}" type="image/x-icon">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">

</head>

<body>
   
   
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand me-2" href="#">
            <i class="fas fa-user-shield me-2"></i>{% if user.is_authenticated %}
                                                    {% for group in user.groups.all %}
                                                    {{ group.name }}
                                                    {% endfor %}
                                                
                                                    {% endif %}
        </a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if perms.streaming.view_videos %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'administrador' %}"><i class="fas fa-home me-1"></i> Inicio</a>
                </li>
                {% endif %}
               {% if perms.auth.view_user %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios' %}"><i class="fas fa-users me-1"></i> Usuarios</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'espacio_disco' %}"><i class="fa-solid fa-box-archive"></i> Espacio Libre</a>
                </li>
                {% if perms.streaming.view_historial %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'history' %}"><i class="fa-solid fa-notes-medical"></i> historial</a>
                </li>
                 {% endif %}
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'img/perf.png' %}" alt="Imagen de perfil del usuario" class="rounded-circle profile-img me-1">
                        <span class="d-none d-lg-inline">{{ user.username }}</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li><a class="dropdown-item" href="{% url 'perfil' %}"><i class="fas fa-user-circle me-2"></i>Perfil</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item text-danger" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt me-2"></i> Salir</a></li>
                    </ul>
                </li>
            </ul>

            <button class="btn ms-2" id="themeToggle" aria-label="Cambiar tema">
                <i class="fas fa-moon" style="color: rgb(255, 255, 255);" id="themeIcon"></i>
            </button>
        </div>
    </div>
</nav>
    {% block content %}
    {% endblock %}


      
     <script src="{% static 'estilos/js/tablas.js' %}" ></script>
    <script src="{% static 'estilos/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'estilos/js/dark.js' %}"></script>
    
 



</body>
</html>

streaming/templates/base/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'estilos/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/nuevo.css' %}">
  <title>{% block titulo %}  {% endblock %}</title>
  <link rel="shortcut icon" href="{% static './img/logo.png' %}" type="image/x-icon">
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body class="vh-100" style="border: 1px solid black;">
 
  <section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card text-black border-custom">
            <div class="row g-0 rounded-5 caja-lg border-custom">
              <div class="col-lg-6 border-custom">
                <div class="card-body p-md-5 mx-md-4">
                  <div class="text-center">
                       
   
                    <img src="{% static 'img/logo.png' %}" class="img-fluid" style="height:250px;" alt="logo">
                  </div>
                  
                   {% block content %}
                  
                    {% endblock %}
                    
                 </div>
                  
              </div>
              <div class="col-lg-6 d-flex align-items-center gradient-custom-2 border-custom-img" style="
                background: url(../../../static/img/fondo.jpeg) rgba(0, 0, 0, .3);
                background-position: center;
                background-size: cover;
                background-blend-mode: overlay;
              ">
                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                  <form action="" method="POST">
                    <!-- <input pattern=".{3,}" required title="minimo 3 caracteres" maxlength="8">
                    <input type="submit" value="aceptar"> -->
                  </form>
                </div> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <script src="{% static 'estilos/js/bootstrap.bundle.min.js' %}"></script>

streaming/templates/base/videos.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Enlace a Bootstrap CSS (puedes usar un CDN o descargar los archivos) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/nuevo.css' %}">
    <link rel="shortcut icon" href="{% static 'img/logo.ico' %}" type="image/x-icon">

</head>
<body class="fondo">

        {% block content %}
 
        {% endblock %}
      
    <!-- <?php  include "config/videoplayer.php";  ?> Enlace a Bootstrap JS y jQuery (necesarios para algunas funcionalidades de Bootstrap) -->
   
    <script src="{% static 'estilos/js/videoplayer.js' %}" ></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>    